time-actions:
  example:
    name: "Example"
    chance: 50
    servers:
      - 'skyblock'
    time-after-announce: 300000
    discord-message: "The Example event is happening on SkyBlock is 5 minutes!"
    minecraft-message: "Join the SkyBlock server for the Example event in 5 minutes!"
    commands:
      - 'eco give %all_players% 100'
      - 'eco give %random_player% 50;run:10'

placeholder-groups:
  donor:
    - 'donator'
    - 'donator1'

interval-time:
  min: 600000
  max: 900000

discord:
  token: "token goes here"
  channel-id: ""